version: '3.8'

name: echo-ddd-test

services:
# Test DB
  testdb:
    container_name: echo-ddd-testdb
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root
      MYSQL_DATABASE: echo_ddd_test
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/testdb/data:/var/lib/mysql  
      - ./docker/testdb/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/testdb/sql:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    tty: true
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

# Test
  test:
    container_name: echo-ddd-test
    env_file:
      - .env.test
    build:
      target: dev
      context: .
      dockerfile: ./docker/test/Dockerfile
    volumes:
      - ./:/go/src/app
    tty: true
    depends_on:
      testdb:
        condition: service_healthy
