// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/architecture-template/echo-ddd/api/presentation/middleware"
	"github.com/architecture-template/echo-ddd/auth/presentation/controller"
	"github.com/architecture-template/echo-ddd/auth/service"
	"github.com/architecture-template/echo-ddd/config/db"
	"github.com/architecture-template/echo-ddd/infra/dao"
)

// Injectors from wire.go:

// example
func InitializeUserController() controller.UserController {
	sqlHandler := db.NewDB()
	userRepository := dao.NewUserDao(sqlHandler)
	transactionRepository := dao.NewTransactionDao(sqlHandler)
	userService := service.NewUserService(userRepository, transactionRepository)
	userController := controller.NewUserController(userService)
	return userController
}

// user
func InitializeUserMiddleware() middleware.UserMiddleware {
	userMiddleware := middleware.NewUserMiddleware()
	return userMiddleware
}
